spring:
  config:
    import: optional:credentials.yaml
  datasource:
    url: jdbc:postgresql://localhost:5433/freight
    username: ${database.username}
    password: ${database.password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
okta:
  oauth2:
    issuer: ${auth0.issuer}
    audience: ${auth0.audience}
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} - %msg%n"
springdoc:
  swagger-ui:
    path: "/swagger-ui.html"
