spring:
  config:
    import: optional:credentials.yaml
  datasource:
    url: jdbc:postgresql://ep-ancient-rain-a23ruvw5.eu-central-1.aws.neon.tech/vehicle-offer-test-db?sslmode=require
    username: ${database.username}
    password: ${database.password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} - %msg%n"
springdoc:
  swagger-ui:
    path: "/swagger-ui.html"
teleroute:
  username: ${teleroute.username}
  password: ${teleroute.password}
  url: https://api.fx.demo.wktransportservices.com
