spring:
  config:
    import: credentials.yaml
  datasource:
    url: jdbc:postgresql://localhost:5433/freight
    username: ${database.local.username}
    password: ${database.local.password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect