spring:
  config:
    import: optional:credentials.yaml
  datasource:
    url: jdbc:postgresql://localhost:5433/freight
    username: ${database.local.username}
    password: ${database.local.password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
okta:
  oauth2:
    issuer: ${auth0.issuer}
    audience: ${auth0.audience}